### ISSUE TITLE
Deploy application on Heroku

### ISSUE THREAD

**Issue by neenu-chacko** [neenu-chacko/neeto-ui-challenge#8]

**Comment by neenu-chacko** [comment]
I have deployed the app to : 
[neenu-neeto-ui-challenge.herokuapp.com](https://neenu-neeto-ui-challenge.herokuapp.com/)

Credentials:
Username: oliver@example.com
Password: welcome

**Comment by yedhink** [comment]
@neenu-chacko LGTM. Mark this task as completed and go ahead with the next task.
